
[tbody]

[[tbody.tr]]

[[tbody.tr.td]]
span = '11:40-13:10'
div = '2, 4, 6, 8, 10, 12, 14, 16'

[tbody.tr.td.dd]
text = '2306/2 (бывш. 305) ауд.'

[tbody.tr.td.dt]
span = 'Кронверкский пр., д.49, лит.А'

[[tbody.tr.td]]

[tbody.tr.td.dl]
dd = '2306/2 (бывш. 305) ауд.'

[tbody.tr.td.dl.dt]
span = 'Кронверкский пр., д.49, лит.А'

[[tbody.tr.td]]

[tbody.tr.td.dl]
dd = 'Информатика(Лаб)'
text = 'четная неделя'

[tbody.tr.td.dl.dt]
b = 'Малышева Татьяна Алексеевна'

[[tbody.tr.td]]
text = 'Очно - дистанционный'

[tbody.tr.th]
span = 'Чт'

[[tbody.tr]]

[[tbody.tr.td]]
span = '13:30-15:00'
div = '2, 4, 6, 8, 10, 12, 14, 16'

[tbody.tr.td.dd]
text = '2306/2 (бывш. 305) ауд.'

[tbody.tr.td.dt]
span = 'Кронверкский пр., д.49, лит.А'

[[tbody.tr.td]]

[tbody.tr.td.dl]
dd = '2306/2 (бывш. 305) ауд.'

[tbody.tr.td.dl.dt]
span = 'Кронверкский пр., д.49, лит.А'

[[tbody.tr.td]]

[tbody.tr.td.dl]
dd = 'Информатика(Лаб)'
text = 'четная неделя'

[tbody.tr.td.dl.dt]
b = 'Малышева Татьяна Алексеевна'

[[tbody.tr.td]]
text = 'Очно - дистанционный'